// packages/react/src/components/diagrams/Marker/Marker.js
import React from 'react';
import settings from 'carbon-components/src/globals/js/settings';
import { arrowLeft, arrowRight, circle, diamond, square, tee } from "./markerDefinitions";

const { prefix } = settings;

const Marker = ({ d, color, id, orient = "auto", height, width, position = "end", refX, refY }) => {
	const namespace = `${prefix}--cc--marker`;

	const xPos = (position === "end") ? (width / 2) + 0.5 : 0.5;
	const yPos = height / 2;

	return (
		<marker
			className={namespace}
			markerHeight={height}
			markerWidth={width}
			orient={orient}
			id={id}
			refX={refX || xPos}
			refY={refY || yPos}
			markerUnits="userSpaceOnUse"
		>
			<path d={d} style={{ fill: color }} />
		</marker>
	);
};

const ArrowLeftMarker = ({...rest}) => <Marker {...arrowLeft} {...rest} />;
const ArrowRightMarker = ({...rest}) => <Marker {...arrowRight} {...rest} />;
const CircleMarker = ({...rest}) => <Marker {...circle} {...rest} />;
const DiamondMarker = ({...rest}) => <Marker {...diamond} {...rest} />;
const SquareMarker = ({...rest}) => <Marker {...square} {...rest} />;
const TeeMarker = ({...rest}) => <Marker {...tee} {...rest} />;

export {
	Marker as default,
	ArrowLeftMarker,
	ArrowRightMarker,
	CircleMarker,
	DiamondMarker,
	SquareMarker,
	TeeMarker
};

// packages/angular/src/components/graph/marker/marker.component.ts
import { Component, Input, OnInit } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";
import { arrowLeft, arrowRight, circle, diamond, square, tee } from "./markerDefinitions";

const { prefix } = settings;

@Component({
	selector: "[ibm-graph-marker]",
	templateUrl: "./marker.component.html"
})
export class MarkerComponent {
	@Input() d;
	@Input() color;
	@Input() id;
	@Input() orient;
	@Input() height;
	@Input() width;
	@Input() refX;
	@Input() refY;

	namespace = `${prefix}--cc--marker`;
}



<svg:marker
	[ngClass]="namespace"
	[attr.markerHeight]="height"
	[attr.markerWidth]="width"
	[attr.orient]="orient"
	[attr.id]="id"
	[attr.refX]="refX"
	[attr.refY]="refY"
	markerUnits="userSpaceOnUse">
	<svg:path [attr.d]="d" [ngStyle]="{'fill': color}" ></svg:path>
</svg:marker>
