// packages/react/src/diagrams/ShapeNode.tsx
import React from 'react'
import classnames from 'classnames'
import { carbonPrefix } from './utils'

type CssPosition = 'fixed' | 'absolute' | 'relative' | 'static' | 'sticky'

type ShapeNodeProps = {
	shape?: 'circle' | 'square' | 'rounded-square'
	tag?: 'div' | 'button' | 'a'
	title?: string
	subtitle?: string
	description?: string
	renderIcon: React.ReactNode
	href?: string
	size?: string | number
	position?: CssPosition
	bodyPosition?: CssPosition
	stacked?: boolean
}

const ShapeNode: React.FC<
	ShapeNodeProps & React.HTMLAttributes<HTMLAnchorElement | HTMLDivElement | HTMLButtonElement>
> = ({
	shape = 'circle',
	tag = 'div',
	title = 'Title',
	subtitle,
	description,
	renderIcon,
	href,
	size = 48,
	stacked,
	position = 'fixed',
	bodyPosition = 'absolute',
	...rest
}) => {
	const Component = href ? 'a' : rest.onClick ? 'button' : tag

	const namespace = `${carbonPrefix}--cc--shape-node`
	const circleClasses = classnames(namespace, {
		[`${namespace}--stacked`]: stacked,
		[`${namespace}--${shape}`]: shape,
		[`${namespace}--${Component}`]: Component,
		[rest.className as string]: rest.className
	})

	const titleElement = title ? <div className={`${namespace}__title`}>{title}</div> : null
	const subtitleElement = subtitle ? (
		<div className={`${namespace}__subtitle`}>{subtitle}</div>
	) : null
	const descriptionElement = description ? (
		<div className={`${namespace}__description`}>{description}</div>
	) : null

	return (
		<Component
			className={circleClasses}
			style={{ height: size, width: size, position }}
			tabIndex={0}
			{...rest}>
			<div className={`${namespace}__icon`}>{renderIcon}</div>
			<div className={`${namespace}__body`} style={{ position: bodyPosition }}>
				{titleElement}
				{subtitleElement}
				{descriptionElement}
			</div>
		</Component>
	)
}

export default ShapeNode

// packages/angular/src/lib/diagrams/nodes/shape/shape-node.component.ts
import { Component, Input, Output, EventEmitter, TemplateRef, OnInit } from '@angular/core'
import { carbonPrefix } from '../../config'

@Component({
	selector: 'ibm-diagram-shape-node',
	template: `
		<ng-container [ngSwitch]="component">
			<xhtml:div
				*ngSwitchCase="'div'"
				[ngClass]="[
					namespace,
					stacked ? namespace + '--stacked' : '',
					shape ? namespace + '--' + shape : '',
					namespace + '--' + component
				]"
				[ngStyle]="{
					'height.px': size,
					'width.px': size,
					position: position
				}"
				(mouseenter)="mouseEnter.emit($event)"
				(mouseover)="mouseOver.emit($event)"
				(mouseout)="mouseOut.emit($event)"
				(mouseleave)="mouseLeave.emit($event)"
				(mousemove)="mouseMove.emit($event)"
				tabindex="0">
				<ng-container *ngTemplateOutlet="nodeTemplate"></ng-container>
			</xhtml:div>

			<xhtml:button
				*ngSwitchCase="'button'"
				[ngClass]="[
					namespace,
					stacked ? namespace + '--stacked' : '',
					shape ? namespace + '--' + shape : '',
					namespace + '--' + component
				]"
				[ngStyle]="{
					'height.px': size,
					'width.px': size,
					position: position
				}"
				(click)="click.emit($event)"
				(mouseenter)="mouseEnter.emit($event)"
				(mouseover)="mouseOver.emit($event)"
				(mouseout)="mouseOut.emit($event)"
				(mouseleave)="mouseLeave.emit($event)"
				(mousemove)="mouseMove.emit($event)"
				tabindex="0">
				<ng-container *ngTemplateOutlet="nodeTemplate"></ng-container>
			</xhtml:button>

			<xhtml:a
				*ngSwitchCase="'a'"
				[ngClass]="[
					namespace,
					stacked ? namespace + '--stacked' : '',
					shape ? namespace + '--' + shape : '',
					namespace + '--' + component
				]"
				[attr.href]="href"
				[ngStyle]="{
					'height.px': size,
					'width.px': size,
					position: position
				}"
				(mouseenter)="mouseEnter.emit($event)"
				(mouseover)="mouseOver.emit($event)"
				(mouseout)="mouseOut.emit($event)"
				(mouseleave)="mouseLeave.emit($event)"
				(mousemove)="mouseMove.emit($event)"
				tabindex="0">
				<ng-container *ngTemplateOutlet="nodeTemplate"></ng-container>
			</xhtml:a>
		</ng-container>

		<ng-template #nodeTemplate>
			<div *ngIf="renderIcon" attr.class="{{ namespace + '__icon' }}">
				<ng-container *ngTemplateOutlet="renderIcon"></ng-container>
			</div>
			<div attr.class="{{ namespace + '__body' }}" [ngStyle]="{ position: bodyPosition }">
				<div attr.class="{{ namespace + '__title' }}">{{ title }}</div>
				<div attr.class="{{ namespace + '__subtitle' }}">
					{{ subtitle }}
				</div>
			</div>
		</ng-template>
	`
})
export class ShapeNode implements OnInit {
	@Input() as = 'div'
	@Input() href = ''
	@Input() renderIcon?: TemplateRef<any>
	@Input() size = 48
	@Input() stacked = false
	@Input() shape: 'circle' | 'square' | 'rounded-square' = 'circle'
	@Input() subtitle = ''
	@Input() title = ''
	@Input() position: string = 'fixed'
	@Input() bodyPosition: string = 'absolute'

	@Output() click: EventEmitter<any> = new EventEmitter<any>()
	@Output() mouseEnter: EventEmitter<any> = new EventEmitter<any>()
	@Output() mouseOver: EventEmitter<any> = new EventEmitter<any>()
	@Output() mouseOut: EventEmitter<any> = new EventEmitter<any>()
	@Output() mouseLeave: EventEmitter<any> = new EventEmitter<any>()
	@Output() mouseMove: EventEmitter<any> = new EventEmitter<any>()

	namespace = `${carbonPrefix}--cc--shape-node`
	component = 'div'

	ngOnInit() {
		if (this.href) {
			this.component = 'a'
		} else {
			this.component = this.as
		}
	}
}
