// packages/charts-angular/projects/charts-angular/src/stories/chart-wrapper.component.ts
import { Component, Injector, OnInit, Input, ViewContainerRef } from '@angular/core'
import type { ChartTabularData, BaseChartOptions } from '@carbon/charts'

@Component({
  selector: 'chart-wrapper',
  templateUrl: './chart-wrapper.component.html'
})
export class ChartWrapper implements OnInit {
  @Input() demoChart!: any
  @Input() chartType: string = ''
  @Input() data!: ChartTabularData
  @Input() options!: BaseChartOptions
  // @Input() codeSandbox!: string

  constructor(private viewContainerRef: ViewContainerRef) {}

  ngOnInit(): void {
    console.log(this.demoChart)
  }

  get injector() {
    const injector = this.viewContainerRef.injector;
    return Injector.create({
      providers: [
        { provide: 'data', useValue: this.data },
        { provide: 'options', useValue: this.options }
      ],
      parent: injector
    })
  }

  async openCloudSandbox() {
		console.log('Click')
		try {
			const response = await fetch('https://codesandbox.io/api/v1/sandboxes', {
				method: 'POST',
				// body: JSON.stringify(this.codeSandbox),
				headers: { 'Content-Type': 'application/json' }
			})
	
			if (!response.ok) {
				throw new Error('Network response from CodeSandbox was not ok')
			}
			const { data } = await response.json()
			const sandboxUrl = `https://codesandbox.io/p/sandbox/${data.sandbox_id}`
			window.open(sandboxUrl, '_blank')
		} catch (error) {
			console.error('There was a problem opening the Cloud Sandbox:', error)
			throw error
		}
	}
}
<div class="container theme--white">
  <div class="v10-banner">
    This version relies on <b>Carbon v11</b>. If you're using Carbon v10, <a href="https://carbon-charts-0x.netlify.app" target="_blank" rel="noreferrer">see the legacy demo site</a>
  </div>
  <h3>
    <b>Component:</b>
    <span class="cds--tag cds--tag--green component-name">{{chartType}}</span>
  </h3>
  <p class="props">
    <b>Props:</b> data, <a href="https://carbon-design-system.github.io/carbon-charts/documentation/modules/_interfaces_charts_.html" target="_blank">options</a>
  </p>

  <div class="marginTop-30" id="chart-demo">
    <ng-container *ngComponentOutlet="demoChart; injector: injector;"></ng-container>
	</div>

  <h3 class="marginTop-30">Code sample</h3>
  <a href="javascript:void(0)" (click)="openCloudSandbox()">
    <img
      src="https://codesandbox.io/static/img/play-codesandbox.svg"
      alt="Edit on CodeSandbox"
      class="marginTop"
    />
  </a>

  <div class="cds--snippet cds--snippet--multi cds--snippet--expand marginTop-30" data-code-snippet>
    <div class="cds--snippet-container" aria-label="Code Snippet Text">
      <pre>
        <code>
          &lt;{{ chartType }} [data]="data" [options]="options" &gt;&lt;/{{ chartType }}&gt;
        </code>
      </pre>
    </div>
  </div>
</div>

// packages/svelte/stories/ChartWrapper.svelte
<script>
	export let DemoComponent = undefined;
	export let chartType = undefined;
	export let demo = {};
</script>

<div class="container theme--white">
	<div class="v10-banner">
		This version relies on <b>Carbon v11</b>. If you're using Carbon v10,
		<a
			href="https://carbon-charts-0x.netlify.app"
			target="_blank"
			rel="noreferrer">see the legacy demo site</a
		>
	</div>

	<h3>
		<b>Component:</b>
		<span class="cds--tag cds--tag--green component-name">
			{`<${chartType} />`}
		</span>
	</h3>

	<p class="props">
		<b>Props:</b>
		data,
		<a
			href="https://carbon-design-system.github.io/carbon-charts/documentation/modules/_interfaces_charts_.html"
			target="_blank"
		>
			options
		</a>
	</p>

	<div class="marginTop-30" id="chart-demo">
		<svelte:component
			this={DemoComponent}
			data={demo.data}
			options={demo.options}
		/>
	</div>

	{#if demo.codesandbox.svelte}
		<h3 class="marginTop-30">Code sample</h3>

		<a href={demo.codesandbox.svelte} target="_blank">
			<img
				src="https://codesandbox.io/static/img/play-codesandbox.svg"
				alt="Edit on CodeSandbox"
				class="marginTop"
			/>
		</a>
	{/if}

	<div
		class="cds--snippet cds--snippet--multi cds--snippet--expand marginTop-30"
		data-code-snippet
	>
		<div class="cds--snippet-container" aria-label="Code Snippet Text">
			<pre>
        <code>
          <span class="token tag">{`<${chartType}`}</span> <span
						class="token attr-name">{`{data}`}</span
					> <span class="token attr-name">{`{options}`}</span> <span
						class="token tag">{`/>`}</span
					>
        </code>
      </pre>
		</div>
	</div>
</div>
