// packages/react/src/components/graph/card/card.js
import React from 'react';
import settings from 'carbon-components/src/globals/js/settings';
import classnames from 'classnames';

const { prefix } = settings;

export default ({ description, label, onClick = () => {}, renderAction, renderIcon, stacked, title }) => {
	const namespace = `${prefix}--cc--card`;
	const icon = renderIcon ? (
		<div className={`${namespace}__icon`}>{renderIcon}</div>
	) : null;

	const cardClasses = classnames(namespace, {
		[`${namespace}--stacked`]: stacked,
	});

	const action = renderAction ? <div className={`${namespace}__action`}>{renderAction}</div> : null;
	const labelElement = label ? <div className={`${namespace}__label`}>{label}</div> : null;

	return (
		<div className={cardClasses} tabIndex={0} onClick={() => onClick()}>
			{icon}
			<div className={`${namespace}__body`}>
				<div className={`${namespace}__title`}>{title}</div>
				<div className={`${namespace}__description`}>{description}</div>
				{labelElement}
			</div>
			{action}
		</div>
	);
};

// packages/angular/src/components/graph/card/card.component.ts
import { Component, Input, Output, EventEmitter, TemplateRef } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";

const { prefix } = settings;

@Component({
	selector: "ibm-graph-card",
	template: `
	<div [ngClass]="[namespace, stacked ? namespace + '--stacked' : '']" tabindex="0" (click)="onClick.emit($event)">
		<div *ngIf="renderIcon" attr.class="{{ namespace + '__icon' }}" >
			<ng-container *ngTemplateOutlet="renderIcon"></ng-container>
		</div>
		<div attr.class="{{ namespace + '__body' }}">
            <div attr.class="{{ namespace + '__title' }}">{{title}}</div>
            <div attr.class="{{ namespace + '__description' }}">{{description}}</div>
			<div *ngIf="label" attr.class="{{ namespace + '__label' }}">{{label}}</div>
		</div>
		<div *ngIf="renderAction" attr.class="{{ namespace + '__action' }}" >
			<ng-container *ngTemplateOutlet="renderAction"></ng-container>
		</div>
	</div>
	`
})

export class CardComponent {
	@Input() description;
	@Input() label;
	@Input() stacked;
	@Input() title;
	@Input() renderAction: TemplateRef<any>;
	@Input() renderIcon: TemplateRef<any>;
	@Output() onClick = new EventEmitter<any>();

	namespace = `${prefix}--cc--card`;
}
