// packages/react/src/components/card/card.js
import React from "react";
import settings from "carbon-components/src/globals/js/settings";

const { prefix } = settings;

export default ({ title, description, icon }) => {
	const namespace = `${prefix}--cc--card`

	return (
		<div className={namespace} tabIndex={0}>
		<div className={`${namespace}__icon`}>{icon}</div>
		<div className={`${namespace}__body`}>
			<div className={`${namespace}__title`}>{title}</div>
			<div className={`${namespace}__description`}>{description}</div>
		</div>
		</div>
	)
};

// packages/angular/src/components/graph/card/card.component.ts
import { Component, Input, Output, EventEmitter, OnInit, TemplateRef } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";

const { prefix } = settings;

@Component({
	selector: "ibm-graph-card",
	template: `
	<div [attr.class]="namespace" tabindex="0" (click)="onClick.emit($event)">
		<div *ngIf="renderIcon" attr.class="{{ namespace + '__icon' }}" >
			<ng-container *ngTemplateOutlet="renderIcon"></ng-container>
		</div>
		<div attr.class="{{ namespace + '__body' }}" transform="translate(80,28)">
            <div attr.class="{{ namespace + '__title' }}">{{title}}</div>
            <div attr.class="{{ namespace + '__description' }}" transform="translate(0,20)">{{description}}</div>
        </div>
	</div>
	`
})

export class CardComponent {
	@Input() title;
	@Input() description;
	@Input() renderIcon: TemplateRef<any>;
	@Output() onClick = new EventEmitter<any>();

	namespace = `${prefix}--cc--card`;
}
