// packages/angular/src/lib/diagrams/edges/marker/marker.component.ts
import { Component, Input, OnInit } from '@angular/core'
import { arrowLeft, arrowRight, circle, diamond, square, tee } from '@carbon/charts'
import { carbonPrefix } from '../../config'

const template = `
<svg:marker
	[ngClass]="namespace"
	[attr.markerHeight]="height"
	[attr.markerWidth]="width"
	[attr.orient]="orient"
	[attr.id]="id"
	[attr.refX]="refX"
	[attr.refY]="refY"
	markerUnits="userSpaceOnUse">
	<svg:path [attr.d]="d" [ngStyle]="{'fill': color}" ></svg:path>
</svg:marker>
`

@Component({
	selector: '[ibm-graph-marker]',
	template
})
export class Marker {
	@Input() d = ''
	@Input() color = ''
	@Input() id = ''
	@Input() orient: string | number = 'auto'
	@Input() height: string | number = ''
	@Input() width: string | number = ''
	@Input() refX: string | number = ''
	@Input() refY: string | number = ''
	@Input() position: 'start' | 'end' = 'end'

	namespace = `${carbonPrefix}--cc--marker`

	setAttributes = ({
		d,
		id,
		height,
		width
	}: {
		d: string
		id: string
		height: number
		width: number
	}) => {
		const xPos = this.position === 'end' ? width / 2 + 0.5 : 0.5
		const yPos = height / 2

		this.d = this.d || d
		this.id = this.id || id
		this.height = this.height || height
		this.width = this.width || width
		this.refX = this.refX || xPos
		this.refY = this.refY || yPos
	}
}

@Component({
	selector: '[ibm-graph-marker-arrow-left]',
	template
})
export class MarkerArrowLeft extends Marker implements OnInit {
	ngOnInit() {
		this.setAttributes({ ...arrowLeft })
	}
}
@Component({
	selector: '[ibm-graph-marker-arrow-right]',
	template
})
export class MarkerArrowRight extends Marker implements OnInit {
	ngOnInit() {
		this.setAttributes({ ...arrowRight })
	}
}
@Component({
	selector: '[ibm-graph-marker-circle]',
	template
})
export class MarkerShapeNode extends Marker implements OnInit {
	ngOnInit() {
		this.setAttributes({ ...circle })
	}
}
@Component({
	selector: '[ibm-graph-marker-diamond]',
	template
})
export class MarkerDiamond extends Marker implements OnInit {
	ngOnInit() {
		this.setAttributes({ ...diamond })
	}
}
@Component({
	selector: '[ibm-graph-marker-square]',
	template
})
export class MarkerSquare extends Marker implements OnInit {
	ngOnInit() {
		this.setAttributes({ ...square })
	}
}
@Component({
	selector: '[ibm-graph-marker-tee]',
	template
})
export class MarkerTee extends Marker implements OnInit {
	ngOnInit() {
		this.setAttributes({ ...tee })
	}
}

// packages/react/src/diagrams/Marker.tsx
import React, { SVGProps } from 'react'
import classnames from 'classnames'
import { carbonPrefix } from './utils'
import { arrowLeft, arrowRight, circle, diamond, square, tee } from '@carbon/charts'

interface MarkerProps extends SVGProps<SVGMarkerElement> {
	id?: string
	d?: string
	color?: string
	position?: 'start' | 'end'
	orient?: string | number
	height?: number
	width?: number
	refX?: number
	refY?: number
}

const Marker: React.FC<MarkerProps> = ({
	color,
	d,
	id,
	orient = 'auto',
	height,
	width,
	position = 'end',
	className,
	refX,
	refY,
	...rest
}) => {
	const namespace = `${carbonPrefix}--cc--marker`
	const classes = classnames(namespace, className)

	const xPos = position === 'end' ? (width || 0) / 2 + 0.5 : 0.5
	const yPos = (height || 0) / 2

	return (
		<marker
			className={classes}
			markerHeight={height}
			markerWidth={width}
			orient={orient}
			id={id}
			refX={refX || xPos}
			refY={refY || yPos}
			markerUnits="userSpaceOnUse"
			{...rest}>
			<path d={d} style={{ fill: color }} />
		</marker>
	)
}

const ArrowLeftMarker: React.FC<Omit<MarkerProps, 'd'>> = (props) => <Marker d={arrowLeft.d} {...props} />
const ArrowRightMarker: React.FC<Omit<MarkerProps, 'd'>> = (props) => <Marker d={arrowRight.d} {...props} />
const CircleMarker: React.FC<Omit<MarkerProps, 'd'>> = (props) => <Marker d={circle.d} {...props} />
const DiamondMarker: React.FC<Omit<MarkerProps, 'd'>> = (props) => <Marker d={diamond.d} {...props} />
const SquareMarker: React.FC<Omit<MarkerProps, 'd'>> = (props) => <Marker d={square.d} {...props} />
const TeeMarker: React.FC<Omit<MarkerProps, 'd'>> = (props) => <Marker d={tee.d} {...props} />

export {
	Marker,
	ArrowLeftMarker,
	ArrowRightMarker,
	CircleMarker,
	DiamondMarker,
	SquareMarker,
	TeeMarker
}
