// packages/angular/src/components/graph/edge/edge.component.ts
import { Component, Input } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";
import { straight } from "./buildPath";

const { prefix } = settings;

@Component({
	selector: "[ibm-graph-edge]",
	template: `
	<svg:g [ngClass]="[namespace, variant ? namespace + '--' + variant : '']">
		<svg:path
			[ngClass]="namespace + '__container'"
			[attr.d]="path ? path : straight(source, target)"
		/>
		<svg:path
			[ngClass]="namespace + '__outer'"
			[attr.d]="path ? path : straight(source, target)"
		/>
		<svg:path
			[ngClass]="namespace + '__inner'"
			[attr.d]="path ? path : straight(source, target)"
		/>
	</svg:g>

	`
})

export class EdgeComponent {
	@Input() source;
	@Input() target;
	@Input() variant;
	@Input() path;

	pathClasses;
	namespace = `${prefix}--cc--edge`;
	straight = straight;
}

// packages/react/src/components/graph/edge/edge.js
import React from 'react';
import settings from 'carbon-components/src/globals/js/settings';
import { straight } from './buildPath';
import classnames from 'classnames';

const { prefix } = settings;

export default ({
	source,
	target,
	variant = null,
	path = straight(source, target),
}) => {
	const namespace = `${prefix}--cc--edge`;

	const pathClasses = classnames(namespace, {
		[`${namespace}--${variant}`]: variant,
	});

	return (
		<g className={pathClasses}>
			<path d={path} className={`${namespace}__container`} />
			<path d={path} className={`${namespace}__outer`} />
			<path d={path} className={`${namespace}__inner`} />
		</g>
	);
};
