// packages/angular/src/components/diagrams/shape-node/shape-node.component.ts
import { Component, Input, Output, EventEmitter, TemplateRef, OnInit } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";

const { prefix } = settings;

@Component({
	selector: "ibm-diagram-shape-node",
	template: `
	<ng-container [ngSwitch]="component">

		<xhtml:div
			*ngSwitchCase="'div'"
			[ngClass]="[
				namespace,
				stacked ? namespace + '--stacked' : '',
				shape ? namespace + '--' + shape : '',
				namespace + '--' + component
			]"
			[ngStyle]="{'height.px': size, 'width.px': size}"
			(mouseenter)="onMouseEnter.emit($event)"
			(mouseover)="onMouseOver.emit($event)"
			(mouseout)="onMouseOut.emit($event)"
			(mouseleave)="onMouseLeave.emit($event)"
			(mousemove)="onMouseMove.emit($event)"
			tabindex="0"
		>
			<ng-container *ngTemplateOutlet="nodeTemplate"></ng-container>
		</xhtml:div>

		<xhtml:button
			*ngSwitchCase="'button'"
			[ngClass]="[
				namespace,
				stacked ? namespace + '--stacked' : '',
				shape ? namespace + '--' + shape : '',
				namespace + '--' + component
			]"
			[ngStyle]="{'height.px': size, 'width.px': size}"
			(click)="onClick.emit($event)"
			(mouseenter)="onMouseEnter.emit($event)"
			(mouseover)="onMouseOver.emit($event)"
			(mouseout)="onMouseOut.emit($event)"
			(mouseleave)="onMouseLeave.emit($event)"
			(mousemove)="onMouseMove.emit($event)"
			tabindex="0"
		>
			<ng-container *ngTemplateOutlet="nodeTemplate"></ng-container>
		</xhtml:button>

		<xhtml:a
			*ngSwitchCase="'a'"
			[ngClass]="[
				namespace,
				stacked ? namespace + '--stacked' : '',
				shape ? namespace + '--' + shape : '',
				namespace + '--' + component
			]"
			[attr.href]="href"
			[ngStyle]="{'height.px': size, 'width.px': size}"
			(mouseenter)="onMouseEnter.emit($event)"
			(mouseover)="onMouseOver.emit($event)"
			(mouseout)="onMouseOut.emit($event)"
			(mouseleave)="onMouseLeave.emit($event)"
			(mousemove)="onMouseMove.emit($event)"
			tabindex="0"
		>
			<ng-container *ngTemplateOutlet="nodeTemplate"></ng-container>
		</xhtml:a>
	</ng-container>

	<ng-template #nodeTemplate>
		<div *ngIf="renderIcon" attr.class="{{ namespace + '__icon' }}" >
			<ng-container *ngTemplateOutlet="renderIcon"></ng-container>
		</div>
		<div attr.class="{{ namespace + '__body' }}">
            <div attr.class="{{ namespace + '__title' }}">{{title}}</div>
            <div attr.class="{{ namespace + '__subtitle' }}">{{subtitle}}</div>
        </div>
	</ng-template>
	`
})

export class ShapeNodeComponent implements OnInit {
	@Input() as: String = "div";
	@Input() href: String = null;
	@Input() renderIcon: TemplateRef<any>;
	@Input() size: Number = 48;
	@Input() stacked: Boolean;
	@Input() shape: "circle" | "square" | "rounded-square" = "circle";
	@Input() subtitle: String;
	@Input() title: String;

	@Output() onClick = new EventEmitter<any>();
	@Output() onMouseEnter = new EventEmitter<any>();
	@Output() onMouseOver = new EventEmitter<any>();
	@Output() onMouseOut = new EventEmitter<any>();
	@Output() onMouseLeave = new EventEmitter<any>();
	@Output() onMouseMove = new EventEmitter<any>();

	namespace = `${prefix}--cc--shape-node`;
	component = "div";

	ngOnInit() {
		if (this.href) {
			this.component = "a";
		} else if (this.onClick) {
			this.component = "button";
		}
	}

}

// packages/react/src/components/diagrams/ShapeNode/ShapeNode.js
import React from 'react';
import PropTypes from 'prop-types';
import settings from 'carbon-components/src/globals/js/settings';
import classnames from 'classnames';

const { prefix } = settings;

const ShapeNode = ({
	as = 'div',
	href = null,
	onClick = null,
	onMouseEnter = null,
	onMouseOver = null,
	onMouseOut = null,
	onMouseLeave = null,
	onMouseMove = null,
	renderIcon,
	size = 48,
	stacked,
	shape = 'circle',
	subtitle,
	title,
}) => {
	const namespace = `${prefix}--cc--shape-node`;

	let Component = 'div';

	if (href) {
		Component = 'a';
	} else if (onClick) {
		Component = 'button';
	}

	const circleClasses = classnames(namespace, {
		[`${namespace}--stacked`]: stacked,
		[`${namespace}--${shape}`]: shape,
		[`${namespace}--${Component}`]: Component,
	});

	const titleElement = title ? (
		<div className={`${namespace}__title`}>{title}</div>
	) : null;
	const subtitleElement = subtitle ? (
		<div className={`${namespace}__subtitle`}>{subtitle}</div>
	) : null;

	return (
		<Component
			className={circleClasses}
			onClick={onClick}
			onMouseEnter={onMouseEnter}
			onMouseOver={onMouseOver}
			onMouseOut={onMouseOut}
			onMouseLeave={onMouseLeave}
			onMouseMove={onMouseMove}
			style={{ height: size, width: size }}
			tabIndex={0}>
			<div className={`${namespace}__icon`}>{renderIcon}</div>
			<div className={`${namespace}__body`}>
				{titleElement}
				{subtitleElement}
			</div>
		</Component>
	);
};

ShapeNode.propTypes = {
	/** Provide a custom element to be rendered instead of the default */
	as: PropTypes.oneOf(['div', 'a', 'button']),

	/**
	 * Optionally specify an href for the CardNode to become an `<a>` element
	 */
	href: PropTypes.string,

	/**
	 * Provide an optional function to be called when the CardNode
	 * is clicked, turning the CardNode into a `<button>` element
	 */
	onClick: PropTypes.func,

	/**
	 * Provide an optional function to be called for the onMouseEnter event
	 */
	onMouseEnter: PropTypes.func,

	/**
	 * Provide an optional function to be called for the onMouseOver event
	 */
	onMouseOver: PropTypes.func,

	/**
	 * Provide an optional function to be called for the onMouseOut event
	 */
	onMouseOut: PropTypes.func,

	/**
	 * Provide an optional function to be called for the onMouseLeave event
	 */
	onMouseLeave: PropTypes.func,

	/**
	 * Provide an optional function to be called for the onMouseMove event
	 */
	onMouseMove: PropTypes.func,

	/**
	 * Function to render your own icon in the underlying button
	 */
	renderIcon: PropTypes.oneOfType([PropTypes.func, PropTypes.object]),

	/**
	 * Specify the height and width of the shape
	 * Can be defined using any CSS length unit (px, %, rem)
	 */
	size: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),

	/**
	 * Specify whether the node displays a stacked effect
	 */
	stacked: PropTypes.bool,

	/**
	 * Specify the shape of the node
	 */
	shape: PropTypes.oneOf(['circle', 'square', 'rounded-square']),

	/**
	 * Specify the node's subtitle
	 */
	subtitle: PropTypes.string,

	/**
	 * Specify the node's title
	 */
	title: PropTypes.string,
};

export default ShapeNode;
