// packages/svelte/src/lib/AreaChart.svelte
<script lang="ts">
	import {
		AreaChart as AreaChartCore,
		type AreaChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: AreaChartOptions
	export let data: ChartTabularData
	export let chart: AreaChartCore | null = null
	export let ref: HTMLDivElement | null = null
</script>

<BaseChart
	{...$$restProps}
	Chart={AreaChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/react/src/charts/area-chart.tsx
import React from 'react'
import {
	AreaChart as AreaChartCore,
	type AreaChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class AreaChart extends BaseChart<AreaChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new AreaChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as AreaChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => { if (chartRef) this.chartRef = chartRef }} className="chart-holder"></div>
	}
}
