// packages/svelte/src/lib/BarChartGrouped.svelte
<script lang="ts">
	import {
		GroupedBarChart as GroupedBarChartCore,
		type BarChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: BarChartOptions
	export let data: ChartTabularData
	export let chart: GroupedBarChartCore
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={GroupedBarChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/react/src/charts/bar-chart-grouped.tsx
import React from 'react'
import {
	GroupedBarChart as GroupedBarChartCore,
	type BarChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class GroupedBarChart extends BaseChart<BarChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new GroupedBarChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as BarChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => { if (chartRef) this.chartRef = chartRef }} className="chart-holder"></div>
	}
}
