// packages/charts-svelte/src/lib/BulletChart.svelte
<script lang="ts">
	import { BulletChart, type BulletChartOptions, type ChartTabularData } from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: BulletChart
	export let options: BulletChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart {...$$restProps}
	Chart={BulletChart}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy
/>

// packages/react/src/charts/BulletChart.tsx
import React from 'react'
import { BulletChart as BulletChartCore, type BulletChartOptions, type ChartTabularData } from '@carbon/charts'
import BaseChart from './BaseChart'

export default class BulletChart extends BaseChart<BulletChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: BulletChartOptions) {
		return new BulletChartCore(chartRef, { data, options })
	}
}
