// packages/svelte/src/lib/CirclePackChart.svelte
<script lang="ts">
	import {
		CirclePackChart as CirclePackChartCore,
		type CirclePackChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: CirclePackChartOptions
	export let data: ChartTabularData
	export let chart: CirclePackChartCore
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={CirclePackChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/react/src/charts/CirclePackChart.tsx
import React from 'react'
import {
	CirclePackChart as CirclePackChartCore,
	type CirclePackChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './BaseChart'

export default class CirclePackChart extends BaseChart<CirclePackChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: CirclePackChartOptions) {
		return new CirclePackChartCore(chartRef, { data, options })
	}
}
