// packages/charts-svelte/src/lib/ComboChart.svelte
<script lang="ts">
	import { ComboChart, type ComboChartOptions, type ChartTabularData } from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: ComboChart
	export let options: ComboChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart {...$$restProps}
	Chart={ComboChart}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy
/>

// packages/react/src/charts/ComboChart.tsx
import React from 'react'
import { ComboChart as ComboChartCore, type ComboChartOptions, type ChartTabularData } from '@carbon/charts'
import BaseChart from './BaseChart'

export default class ComboChart extends BaseChart<ComboChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: ComboChartOptions) {
		return new ComboChartCore(chartRef, { data, options })
	}
}
