// packages/svelte/src/lib/DonutChart.svelte
<script lang="ts">
	import {
		DonutChart as DonutChartCore,
		type DonutChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: DonutChartOptions
	export let data: ChartTabularData
	export let chart: DonutChartCore
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={DonutChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/react/src/charts/donut-chart.tsx
import React from 'react'
import {
	DonutChart as DonutChartCore,
	type DonutChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class DonutChart extends BaseChart<DonutChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new DonutChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as DonutChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
	}
}
