// packages/svelte/src/lib/GaugeChart.svelte
<script lang="ts">
	import {
		GaugeChart as GaugeChartCore,
		type GaugeChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: GaugeChartOptions
	export let data: ChartTabularData
	export let chart: GaugeChartCore | undefined = undefined
	export let ref: HTMLDivElement | undefined = undefined
</script>

<BaseChart
	{...$$restProps}
	Chart={GaugeChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/react/src/charts/gauge-chart.tsx
import React from 'react'
import {
	GaugeChart as GaugeChartCore,
	type GaugeChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class GaugeChart extends BaseChart<GaugeChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new GaugeChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as GaugeChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => { if (chartRef) this.chartRef = chartRef }} className="chart-holder"></div>
	}
}
