// packages/svelte/src/lib/LineChart.svelte
<script lang="ts">
	import {
		LineChart as LineChartCore,
		type LineChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: LineChartCore
	export let options: LineChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={LineChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/react/src/charts/LineChart.tsx
import React from 'react'
import {
	LineChart as LineChartCore,
	type LineChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './BaseChart'

export default class LineChart extends BaseChart<LineChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: LineChartOptions) {
		return new LineChartCore(chartRef, { data, options })
	}
}
