// packages/svelte/src/lib/MeterChart.svelte
<script lang="ts">
	import {
		MeterChart as MeterChartCore,
		type MeterChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: MeterChartOptions
	export let data: ChartTabularData
	export let chart: MeterChartCore | null  = null
	export let ref: HTMLDivElement | null  = null
</script>

<BaseChart
	{...$$restProps}
	Chart={MeterChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/react/src/charts/MeterChart.tsx
import React from 'react'
import { MeterChart as MeterChartCore, type MeterChartOptions, type ChartTabularData } from '@carbon/charts'
import BaseChart from './BaseChart'

export default class MeterChart extends BaseChart<MeterChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: MeterChartOptions) {
		return new MeterChartCore(chartRef, { data, options })
	}
}
