// packages/charts-svelte/src/lib/PieChart.svelte
<script lang="ts">
	import { PieChart, type PieChartOptions, type ChartTabularData } from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: PieChart
	export let options: PieChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={PieChart}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/react/src/charts/PieChart.tsx
import React from 'react'
import { PieChart as PieChartCore, type PieChartOptions, type ChartTabularData } from '@carbon/charts'
import BaseChart from './BaseChart'

export default class PieChart extends BaseChart<PieChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: PieChartOptions) {
		return new PieChartCore(chartRef, { data, options })
	}
}
