// packages/svelte/src/lib/RadarChart.svelte
<script lang="ts">
	import {
		RadarChart as RadarChartCore,
		type RadarChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: RadarChartOptions
	export let data: ChartTabularData
	export let chart: RadarChartCore
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={RadarChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/react/src/charts/RadarChart.tsx
import React from 'react'
import {
	RadarChart as RadarChartCore,
	type RadarChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './BaseChart'

export default class RadarChart extends BaseChart<RadarChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: RadarChartOptions) {
		return new RadarChartCore(chartRef, { data, options })
	}
}
