// packages/charts-svelte/src/lib/StackedAreaChart.svelte
<script lang="ts">
	import { StackedAreaChart, type StackedAreaChartOptions, type ChartTabularData } from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: StackedAreaChart
	export let options: StackedAreaChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart {...$$restProps}
	Chart={StackedAreaChart}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy
/>

// packages/react/src/charts/StackedAreaChart.tsx
import React from 'react'
import {
	StackedAreaChart as StackedAreaChartCore,
	type StackedAreaChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './BaseChart'

export default class StackedAreaChart extends BaseChart<StackedAreaChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: StackedAreaChartOptions) {
		return new StackedAreaChartCore(chartRef, { data, options })
	}
}
