// packages/charts-svelte/src/lib/TreeChart.svelte
<script lang="ts">
	import { TreeChart, type TreeChartOptions, type ChartTabularData } from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: TreeChart
	export let options: TreeChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart {...$$restProps}
	Chart={TreeChart}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy
/>

// packages/react/src/charts/TreeChart.tsx
import React from 'react'
import {
	TreeChart as TreeChartCore,
	type TreeChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './BaseChart'

export default class TreeChart extends BaseChart<TreeChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: TreeChartOptions) {
		return new TreeChartCore(chartRef, { data, options })
	}
}
