// packages/svelte/src/lib/TreemapChart.svelte
<script lang="ts">
	import {
		TreemapChart as TreemapChartCore,
		type TreemapChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: TreemapChartCore
	export let options: TreemapChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={TreemapChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/react/src/charts/treemap-chart.tsx
import React from 'react'
import {
	TreemapChart as TreemapChartCore,
	type TreemapChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class TreemapChart extends BaseChart<TreemapChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new TreemapChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as TreemapChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => { if (chartRef) this.chartRef = chartRef }} className="chart-holder"></div>
	}
}
