// packages/svelte/src/lib/TreeChart.svelte
<script lang="ts">
	import {
		TreeChart as TreeChartCore,
		type TreeChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: TreeChartOptions
	export let data: ChartTabularData
	export let chart: TreeChartCore
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={TreeChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/react/src/charts/tree-chart.tsx
import React from 'react'
import {
	TreeChart as TreeChartCore,
	type TreeChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class TreeChart extends BaseChart<TreeChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new TreeChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as TreeChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
	}
}
