// packages/charts-svelte/src/lib/WordCloudChart.svelte
<script lang="ts">
	import { WordCloudChart, type WorldCloudChartOptions, type ChartTabularData } from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: WordCloudChart
	export let options: WorldCloudChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart {...$$restProps}
	Chart={WordCloudChart}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy
/>

// packages/react/src/charts/WordCloudChart.tsx
import React from 'react'
import { WordCloudChart as WordCloudChartCore, type WorldCloudChartOptions, type ChartTabularData } from '@carbon/charts'
import BaseChart from './BaseChart'

export default class WordCloudChart extends BaseChart<WorldCloudChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: WorldCloudChartOptions) {
		return new WordCloudChartCore(chartRef, { data, options })
	}
}
