// packages/svelte/src/lib/AlluvialChart.svelte
<script lang="ts">
	import {
		AlluvialChart as AlluvialChartCore,
		type AlluvialChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: AlluvialChartOptions
	export let data: ChartTabularData
	export let chart: AlluvialChartCore
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={AlluvialChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/charts-react/src/charts/alluvial-chart.tsx
import { AlluvialChart as AlluvialChartCore, type AlluvialChartOptions, type ChartTabularData } from '@carbon/charts';
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class AlluvialChart extends BaseChart<AlluvialChartOptions> {
	declare chartRef: HTMLDivElement

  componentDidMount() {
    if (!hasChartBeenInitialized(this.chartRef)) {
      this.chart = new AlluvialChartCore(this.chartRef, {
        data: this.props.data as ChartTabularData,
        options: this.props.options as AlluvialChartOptions
      })
    }
  }

  render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
  }
}
