// packages/charts-angular/projects/charts-angular/src/lib/charts/area-chart.component.ts
import { Component, AfterViewInit } from '@angular/core'

import { BaseChart } from './base-chart.component'

import { AreaChart as AreaChartCore, type AreaChartOptions, type ChartTabularData } from '@carbon/charts'

/**
 * Wrapper around `AreaChart` in carbon charts library
 *
 * Most functions just call their equivalent from the chart library.
 */
@Component({
	selector: 'ibm-area-chart',
	template: ``
})
export class AreaChart extends BaseChart implements AfterViewInit {
	/**
	 * Runs after view init to create a chart, attach it to `chartRef` and draw it.
	 */
	override ngAfterViewInit() {
		this.chart = new AreaChartCore(this.elementRef.nativeElement, {
			data: this.data as ChartTabularData,
			options: this.options as AreaChartOptions
		})

		Object.assign(this, this.chart)
	}
}

// packages/charts-react/src/charts/area-chart.tsx
import {
	AreaChart as AreaChartCore,
	type AreaChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class AreaChart extends BaseChart<AreaChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new AreaChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as AreaChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
	}
}
