// packages/svelte/src/lib/CirclePackChart.svelte
<script lang="ts">
	import {
		CirclePackChart as CirclePackChartCore,
		type CirclePackChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: CirclePackChartOptions
	export let data: ChartTabularData
	export let chart: CirclePackChartCore
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={CirclePackChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/charts-react/src/charts/circle-pack-chart.tsx
import {
	CirclePackChart as CirclePackChartCore,
	type CirclePackChartOptions,
	type ChartConfig,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class CirclePackChart extends BaseChart<CirclePackChartOptions> {
	declare chartRef: HTMLDivElement
	declare props: ChartConfig<CirclePackChartOptions>
	declare chart: CirclePackChartCore

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new CirclePackChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as CirclePackChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
	}
}
