// packages/svelte/src/lib/ComboChart.svelte
<script lang="ts">
	import {
		ComboChart as ComboChartCore,
		type ComboChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: ComboChartCore
	export let options: ComboChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={ComboChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/charts-react/src/charts/combo-chart.tsx
import {
	ComboChart as ComboChartCore,
	type ComboChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class ComboChart extends BaseChart<ComboChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new ComboChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as ComboChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
	}
}
