// packages/svelte/src/lib/MeterChart.svelte
<script lang="ts">
	import {
		MeterChart as MeterChartCore,
		type MeterChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: MeterChartOptions
	export let data: ChartTabularData
	export let chart: MeterChartCore | null  = null
	export let ref: HTMLDivElement | null  = null
</script>

<BaseChart
	{...$$restProps}
	Chart={MeterChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/charts-react/src/charts/meter-chart.tsx
import {
	MeterChart as MeterChartCore,
	type MeterChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class MeterChart extends BaseChart<MeterChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new MeterChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as MeterChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
	}
}
