// packages/react/src/charts/AlluvialChart.tsx
import React from 'react'
import {
	AlluvialChart as AlluvialChartCore,
	type AlluvialChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './BaseChart'

export default class AlluvialChart extends BaseChart<AlluvialChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: AlluvialChartOptions) {
		return new AlluvialChartCore(chartRef, { data, options })
	}
}

// packages/charts-svelte/src/lib/AlluvialChart.svelte
<script lang="ts">
	import { AlluvialChart, type AlluvialChartOptions, type ChartTabularData } from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: AlluvialChart
	export let options: AlluvialChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={AlluvialChart}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />
