// packages/react/src/charts/DonutChart.tsx
import React from 'react'
import {
	DonutChart as DonutChartCore,
	type DonutChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './BaseChart'

export default class DonutChart extends BaseChart<DonutChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: DonutChartOptions) {
		return new DonutChartCore(chartRef, { data, options })
	}
}

// packages/charts-svelte/src/lib/DonutChart.svelte
<script lang="ts">
	import { DonutChart, type DonutChartOptions, type ChartTabularData } from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: DonutChart
	export let options: DonutChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart {...$$restProps}
	Chart={DonutChart}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy
/>
