// packages/react/src/charts/LollipopChart.tsx
import React from 'react'
import { LollipopChart as LollipopChartCore, type LollipopChartOptions, type ChartTabularData } from '@carbon/charts'
import BaseChart from './BaseChart'

export default class LollipopChart extends BaseChart<LollipopChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: LollipopChartOptions) {
		return new LollipopChartCore(chartRef, { data, options })
	}
}

// packages/charts-svelte/src/lib/LollipopChart.svelte
<script lang="ts">
	import { LollipopChart, type LollipopChartOptions, type ChartTabularData } from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: LollipopChart
	export let options: LollipopChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart {...$$restProps}
	Chart={LollipopChart}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy
/>
