// packages/react/src/charts/ScatterChart.tsx
import React from 'react'
import { ScatterChart as ScatterChartCore, type ScatterChartOptions, type ChartTabularData } from '@carbon/charts'
import BaseChart from './BaseChart'

export default class ScatterChart extends BaseChart<ScatterChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: ScatterChartOptions) {
		return new ScatterChartCore(chartRef, { data, options })
	}
}

// packages/charts-svelte/src/lib/ScatterChart.svelte
<script lang="ts">
	import { ScatterChart, type ScatterChartOptions, type ChartTabularData } from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: ScatterChart
	export let options: ScatterChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart {...$$restProps}
	Chart={ScatterChart}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy
/>
