// packages/charts-svelte/src/lib/BarChartSimple.svelte
<script lang="ts">
	import { SimpleBarChart, type BarChartOptions, type ChartTabularData } from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'
	export let chart: SimpleBarChart
	export let options: BarChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart {...$$restProps}
	Chart={SimpleBarChart}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy
/>

// packages/react/src/bar-chart-simple.tsx
import React from "react";

import { SimpleBarChart as SBC } from "@carbon/charts";
import BaseChart from "./base-chart";
import { ChartConfig, BarChartOptions } from "@carbon/charts/interfaces";

type SimpleBarChartProps = ChartConfig<BarChartOptions>;

export default class SimpleBarChart extends BaseChart<BarChartOptions> {
  chartRef!: HTMLDivElement;
  props!: SimpleBarChartProps;
  chart!: SBC;

  componentDidMount() {
    this.chart = new SBC(this.chartRef, {
      data: this.props.data,
      options: this.props.options,
    });
  }

  render() {
    return (
      <div
        ref={(chartRef) => (this.chartRef = chartRef!)}
        className="chart-holder"
      ></div>
    );
  }
}
