// packages/charts-react/src/diagrams/Marker.tsx
import React from 'react'
import classnames from 'classnames'
import { carbonPrefix } from './utils'
import { Component as CarbonComponent } from '@carbon/charts'

type MarkerProps = {
	id?: string
	d?: string
	color?: string
	position?: 'start' | 'end'
	orient?: string | number
	height?: string | number
	width?: string | number
}

const Marker: React.FC<MarkerProps & React.SVGProps<SVGGElement>> = ({
	color,
	d,
	id,
	orient = 'auto',
	height,
	width,
	position = 'end',
	...rest
}: any) => {
	const namespace = `${carbonPrefix}--cc--marker`
	const classes = classnames(namespace, {
		[rest.className]: rest.className
	})

	const xPos = position === 'end' ? width / 2 + 0.5 : 0.5
	const yPos = height / 2

	return (
		<marker
			className={classes}
			markerHeight={height}
			markerWidth={width}
			orient={orient}
			id={id}
			refX={rest.refX || xPos}
			refY={rest.refY || yPos}
			markerUnits="userSpaceOnUse" {...rest}>
			<path d={d} style={{ fill: color }} />
		</marker>
	)
}

const ArrowLeftMarker = ({ ...rest }) => <Marker {...CarbonComponent.arrowLeft} {...rest} />
const ArrowRightMarker = ({ ...rest }) => <Marker {...CarbonComponent.arrowRight} {...rest} />
const CircleMarker = ({ ...rest }) => <Marker {...CarbonComponent.circle} {...rest} />
const DiamondMarker = ({ ...rest }) => <Marker {...CarbonComponent.diamond} {...rest} />
const SquareMarker = ({ ...rest }) => <Marker {...CarbonComponent.square} {...rest} />
const TeeMarker = ({ ...rest }) => <Marker {...CarbonComponent.tee} {...rest} />

export {
	Marker,
	ArrowLeftMarker,
	ArrowRightMarker,
	CircleMarker,
	DiamondMarker,
	SquareMarker,
	TeeMarker
}

// packages/charts-angular/projects/charts-angular/src/lib/diagrams/edges/marker/marker.component.ts
import { Component, Input, OnInit } from '@angular/core'
import { Component as CarbonComponent } from '@carbon/charts'
import { carbonPrefix } from '../../config'

const template = `
<svg:marker
	[ngClass]="namespace"
	[attr.markerHeight]="height"
	[attr.markerWidth]="width"
	[attr.orient]="orient"
	[attr.id]="id"
	[attr.refX]="refX"
	[attr.refY]="refY"
	markerUnits="userSpaceOnUse">
	<svg:path [attr.d]="d" [ngStyle]="{'fill': color}" ></svg:path>
</svg:marker>
`

@Component({
	selector: '[ibm-graph-marker]',
	template
})
export class Marker {
	@Input() d = ''
	@Input() color = ''
	@Input() id = ''
	@Input() orient: string | number = 'auto'
	@Input() height: string | number = ''
	@Input() width: string | number = ''
	@Input() refX: string | number = ''
	@Input() refY: string | number = ''
	@Input() position: 'start' | 'end' = 'end'

	namespace = `${carbonPrefix}--cc--marker`

	setAttributes = ({
		d,
		id,
		height,
		width
	}: {
		d: string
		id: string
		height: number
		width: number
	}) => {
		const xPos = this.position === 'end' ? width / 2 + 0.5 : 0.5
		const yPos = height / 2

		this.d = this.d || d
		this.id = this.id || id
		this.height = this.height || height
		this.width = this.width || width
		this.refX = this.refX || xPos
		this.refY = this.refY || yPos
	}
}

@Component({ selector: '[ibm-graph-marker-arrow-left]', template })
export class MarkerArrowLeft extends Marker implements OnInit {
	ngOnInit() {
		this.setAttributes({ ...CarbonComponent.arrowLeft })
	}
}
@Component({ selector: '[ibm-graph-marker-arrow-right]', template })
export class MarkerArrowRight extends Marker implements OnInit {
	ngOnInit() {
		this.setAttributes({ ...CarbonComponent.arrowRight })
	}
}
@Component({ selector: '[ibm-graph-marker-circle]', template })
export class MarkerShapeNode extends Marker implements OnInit {
	ngOnInit() {
		this.setAttributes({ ...CarbonComponent.circle })
	}
}
@Component({ selector: '[ibm-graph-marker-diamond]', template })
export class MarkerDiamond extends Marker implements OnInit {
	ngOnInit() {
		this.setAttributes({ ...CarbonComponent.diamond })
	}
}
@Component({ selector: '[ibm-graph-marker-square]', template })
export class MarkerSquare extends Marker implements OnInit {
	ngOnInit() {
		this.setAttributes({ ...CarbonComponent.square })
	}
}
@Component({ selector: '[ibm-graph-marker-tee]', template })
export class MarkerTee extends Marker implements OnInit {
	ngOnInit() {
		this.setAttributes({ ...CarbonComponent.tee })
	}
}
