// packages/react/src/diagrams/Edge/Edge.tsx
import React from 'react';
import PropTypes from 'prop-types';

// @ts-ignore
import settings from 'carbon-components/src/globals/js/settings';

// @ts-ignore
import classnames from 'classnames';

import { buildStraightPathString } from '@carbon/charts/components/diagrams/buildPaths';

const { prefix } = settings;

const Edge = ({
	color,
	markerEnd,
	markerStart,
	onMouseEnter = null,
	onMouseOver = null,
	onMouseOut = null,
	onMouseLeave = null,
	onMouseMove = null,
	path,
	source,
	target,
	variant = null,
}: any) => {
	const namespace = `${prefix}--cc--edge`;

	const pathClasses = classnames(namespace, {
		[`${namespace}--${variant}`]: variant,
	});

	const d = path || buildStraightPathString(source, target);

	return (
		<g
			className={pathClasses}
			onMouseEnter={onMouseEnter}
			onMouseOver={onMouseOver}
			onMouseOut={onMouseOut}
			onMouseLeave={onMouseLeave}
			onMouseMove={onMouseMove}>
			<path d={d} className={`${namespace}__container`} />
			<path d={d} className={`${namespace}__outer`} />
			<path
				d={d}
				className={`${namespace}__inner`}
				markerEnd={`url(#${markerEnd})`}
				markerStart={`url(#${markerStart})`}
				style={{ stroke: color }}
			/>
		</g>
	);
};

export default Edge;

Edge.propTypes = {
	/**
	 * Specify the edge's color
	 */
	color: PropTypes.string,

	/**
	 * Specify an ID for a corresponding end marker
	 */
	markerEnd: PropTypes.string,

	/**
	 * Specify an ID for a corresponding start marker
	 */
	markerStart: PropTypes.string,

	/**
	 * Provide an optional function to be called for the onMouseEnter event
	 */
	onMouseEnter: PropTypes.func,

	/**
	 * Provide an optional function to be called for the onMouseOver event
	 */
	onMouseOver: PropTypes.func,

	/**
	 * Provide an optional function to be called for the onMouseOut event
	 */
	onMouseOut: PropTypes.func,

	/**
	 * Provide an optional function to be called for the onMouseLeave event
	 */
	onMouseLeave: PropTypes.func,

	/**
	 * Provide an optional function to be called for the onMouseMove event
	 */
	onMouseMove: PropTypes.func,

	/**
	 * Specify a path string
	 */
	path: PropTypes.string,

	/**
	 * Coordinates for the source element
	 */
	source: PropTypes.shape({
		x: PropTypes.number,
		y: PropTypes.number,
	}),

	/**
	 * Coordinates for the target element
	 */
	target: PropTypes.shape({
		x: PropTypes.number,
		y: PropTypes.number,
	}),

	/**
	 * Specify the variant of the edge
	 */
	variant: PropTypes.oneOf([
		'dash-sm',
		'dash-md',
		'dash-lg',
		'dash-xl',
		'double',
		'tunnel',
	]),
};

// packages/angular/src/components/diagrams/edge/edge.component.ts
import { Component, Input } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";
import { buildStraightPathString } from "@carbon/charts/components/diagrams/buildPaths";

const { prefix } = settings;
interface Coordinates {
	x: number;
	y: number;
}
@Component({
	selector: "[ibm-graph-edge]",
	template: `
	<svg:g [ngClass]="[namespace, variant ? namespace + '--' + variant : '']">
		<svg:path
			[ngClass]="namespace + '__container'"
			[attr.d]="path ? path : straight(source, target)"
		/>
		<svg:path
			[ngClass]="namespace + '__outer'"
			[attr.d]="path ? path : straight(source, target)"
		/>
		<svg:path
			[ngClass]="namespace + '__inner'"
			[attr.d]="path ? path : straight(source, target)"
			[ngStyle]="{'stroke': color}"
			[attr.marker-start]="markerStart ? 'url(#' + markerStart + ')' : ''"
			[attr.marker-end]="markerEnd ? 'url(#' + markerEnd + ')' : ''"
		/>
	</svg:g>
	`
})

export class EdgeComponent {
	@Input() color: string;
	@Input() markerEnd: string;
	@Input() markerStart: string;
	@Input() source: Coordinates;
	@Input() target: Coordinates;
	@Input() variant: "dash-sm" | "dash-md" |  "dash-lg" |  "dash-xl" |  "double" |  "tunnel";
	@Input() path: string;

	pathClasses;
	namespace = `${prefix}--cc--edge`;
	straight = buildStraightPathString;
}
