// packages/react/src/components/diagrams/Edge/Edge.js
import React from 'react';
import PropTypes from 'prop-types';
import settings from 'carbon-components/src/globals/js/settings';
import { buildStraightPathString } from '@carbon/charts/components/diagrams/buildPaths';
import classnames from 'classnames';

const { prefix } = settings;

const Edge = ({
	color,
	markerEnd,
	markerStart,
	path,
	source,
	target,
	variant = null,
}) => {
	const namespace = `${prefix}--cc--edge`;

	const pathClasses = classnames(namespace, {
		[`${namespace}--${variant}`]: variant,
	});

	const d = path || buildStraightPathString(source, target);

	return (
		<g className={pathClasses}>
			<path d={d} className={`${namespace}__container`} />
			<path d={d} className={`${namespace}__outer`} />
			<path d={d} className={`${namespace}__inner`} markerEnd={`url(#${markerEnd})`} markerStart={`url(#${markerStart})`} style={{ stroke: color }} />
		</g>
	);
};

export default Edge;

Edge.propTypes = {
	/**
	* Specify the edge's color
	*/
	color: PropTypes.string,

	/**
	* Specify an ID for a corresponding end marker
	*/
	markerEnd: PropTypes.string,

	/**
	* Specify an ID for a corresponding start marker
	*/
	markerStart: PropTypes.string,

	/**
	* Specify a path string
	*/
	path: PropTypes.string,

	/**
	* Coordinates for the source element
	*/
	source: PropTypes.shape({
		x: PropTypes.number,
		y: PropTypes.number
	}),

	/**
	* Coordinates for the target element
	*/
	target: PropTypes.shape({
		x: PropTypes.number,
		y: PropTypes.number
	}),

	/**
	* Specify the variant of the edge
	*/
	variant: PropTypes.oneOf(['dash-sm', 'dash-md', 'dash-lg', 'dash-xl', 'double', 'tunnel']),
};

// packages/angular/src/components/diagrams/edge/edge.component.ts
import { Component, Input } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";
import { buildStraightPathString } from "@carbon/charts/components/diagrams/buildPaths";

const { prefix } = settings;
interface Coordinates {
	x: number;
	y: number;
}
@Component({
	selector: "[ibm-graph-edge]",
	template: `
	<svg:g [ngClass]="[namespace, variant ? namespace + '--' + variant : '']">
		<svg:path
			[ngClass]="namespace + '__container'"
			[attr.d]="path ? path : straight(source, target)"
		/>
		<svg:path
			[ngClass]="namespace + '__outer'"
			[attr.d]="path ? path : straight(source, target)"
		/>
		<svg:path
			[ngClass]="namespace + '__inner'"
			[attr.d]="path ? path : straight(source, target)"
			[ngStyle]="{'stroke': color}"
			[attr.marker-start]="markerStart ? 'url(#' + markerStart + ')' : ''"
			[attr.marker-end]="markerEnd ? 'url(#' + markerEnd + ')' : ''"
		/>
	</svg:g>
	`
})

export class EdgeComponent {
	@Input() color: string;
	@Input() markerEnd: string;
	@Input() markerStart: string;
	@Input() source: Coordinates;
	@Input() target: Coordinates;
	@Input() variant: "dash-sm" | "dash-md" |  "dash-lg" |  "dash-xl" |  "double" |  "tunnel";
	@Input() path: string;

	pathClasses;
	namespace = `${prefix}--cc--edge`;
	straight = buildStraightPathString;
}
