// packages/react/src/components/graph/edge/edge.js
import React from 'react';
import settings from 'carbon-components/src/globals/js/settings';
import { straight } from './buildPath';
import classnames from 'classnames';

const { prefix } = settings;

export default ({
	markerEnd,
	markerStart,
	path,
	source,
	color,
	target,
	variant = null,
}) => {
	const namespace = `${prefix}--cc--edge`;

	const pathClasses = classnames(namespace, {
		[`${namespace}--${variant}`]: variant,
	});

	const d = path || straight(source, target);

	return (
		<g className={pathClasses}>
			<path d={d} className={`${namespace}__container`} />
			<path d={d} className={`${namespace}__outer`} />
			<path d={d} className={`${namespace}__inner`} markerEnd={`url(#${markerEnd})`} markerStart={`url(#${markerStart})`} style={{ stroke: color }} />
		</g>
	);
};

// packages/angular/src/components/diagrams/edge/edge.component.ts
import { Component, Input } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";
import { straight } from "./buildPath";

const { prefix } = settings;

@Component({
	selector: "[ibm-graph-edge]",
	template: `
	<svg:g [ngClass]="[namespace, variant ? namespace + '--' + variant : '']">
		<svg:path
			[ngClass]="namespace + '__container'"
			[attr.d]="path ? path : straight(source, target)"
		/>
		<svg:path
			[ngClass]="namespace + '__outer'"
			[attr.d]="path ? path : straight(source, target)"
		/>
		<svg:path
			[ngClass]="namespace + '__inner'"
			[attr.d]="path ? path : straight(source, target)"
			[ngStyle]="{'stroke': color}"
			[attr.marker-start]="markerStart ? 'url(#' + markerStart + ')' : ''"
			[attr.marker-end]="markerEnd ? 'url(#' + markerEnd + ')' : ''"
		/>
	</svg:g>

	`
})

export class EdgeComponent {
	@Input() color;
	@Input() markerEnd;
	@Input() markerStart;
	@Input() source;
	@Input() target;
	@Input() variant;
	@Input() path;

	pathClasses;
	namespace = `${prefix}--cc--edge`;
	straight = straight;
}
