// packages/angular/src/components/graph/circle/circle.component.ts
import { Component, Input, Output, EventEmitter, OnInit, TemplateRef } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";

const { prefix } = settings;

@Component({
	selector: "ibm-graph-circle",
	template: `
	<div [attr.class]="namespace" [ngStyle]="{'height.px': size, 'width.px': size}" tabindex="0" (click)="onClick.emit($event)">
		<div *ngIf="renderIcon" attr.class="{{ namespace + '__icon' }}" >
			<ng-container *ngTemplateOutlet="renderIcon"></ng-container>
		</div>
		<div attr.class="{{ namespace + '__body' }}" transform="translate(80,28)">
            <div attr.class="{{ namespace + '__title' }}">{{title}}</div>
            <div attr.class="{{ namespace + '__description' }}" transform="translate(0,20)">{{description}}</div>
        </div>
	</div>
	`
})

export class CircleComponent {
	@Input() description;
	@Input() renderIcon: TemplateRef<any>;
	@Input() size = 48;
	@Input() title;

	@Output() onClick = new EventEmitter<any>();

	namespace = `${prefix}--cc--circle`;
}

// packages/react/src/components/graph/circle/circle.js
import React from 'react';
import settings from 'carbon-components/src/globals/js/settings';

const { prefix } = settings;

export default ({ title, description, renderIcon, size = 48 }) => {
	const namespace = `${prefix}--cc--circle`;

	const titleElement = title ? (
		<div className={`${namespace}__title`}>{title}</div>
	) : null;
	const descriptionElement = description ? (
		<div className={`${namespace}__description`}>{description}</div>
	) : null;

	return (
		<div className={namespace} style={{ height: size, width: size }} tabIndex={0}>
			<div className={`${namespace}__icon`}>{renderIcon}</div>
			<div className={`${namespace}__body`}>
				{titleElement}
				{descriptionElement}
			</div>
		</div>
	);
};
