// packages/angular/src/components/diagrams/card-node/card-node-subtitle.component.ts
import { Component } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";

const { prefix } = settings;

@Component({
	selector: "ibm-diagram-card-node-subtitle",
	template: `
	<xhtml:div [ngClass]="namespace">
		<ng-content></ng-content>
	</xhtml:div>
	`
})

export class CardNodeSubtitleComponent {
	namespace = `${prefix}--cc--card-node__subtitle`;
}

// packages/react/src/diagrams/CardNode/CardNodeSubtitle.tsx
import React from 'react';
import PropTypes from 'prop-types';

// @ts-ignore
import settings from 'carbon-components/src/globals/js/settings';

const { prefix } = settings;
const namespace = `${prefix}--cc--card-node`;

const CardNodeSubtitle = ({ children }: any) => (
	<div className={`${namespace}__subtitle`}>{children}</div>
);

export { CardNodeSubtitle };

CardNodeSubtitle.propTypes = {
	/**
	 * Pass in the children that will be rendered within the CardNodeSubtitle
	 */
	children: PropTypes.node,
};
