// packages/angular/src/lib/diagrams/edges/edge.component.ts
import { Component, Input } from '@angular/core'
import { buildStraightPathString } from '@carbon/charts'

import { carbonPrefix } from '../config'

interface Coordinates {
	x: number
	y: number
}
@Component({
	selector: '[ibm-graph-edge]',
	template: `
		<svg:g [ngClass]="[namespace, variant ? namespace + '--' + variant : '']">
			<svg:path
				[ngClass]="namespace + '__container'"
				[attr.d]="path ? path : straight(source, target)" />
			<svg:path
				[ngClass]="namespace + '__outer'"
				[attr.d]="path ? path : straight(source, target)" />
			<svg:path
				[ngClass]="namespace + '__inner'"
				[attr.d]="path ? path : straight(source, target)"
				[ngStyle]="{ stroke: color }"
				[attr.marker-start]="markerStart ? 'url(#' + markerStart + ')' : ''"
				[attr.marker-end]="markerEnd ? 'url(#' + markerEnd + ')' : ''" />
		</svg:g>
	`
})
export class Edge {
	@Input() color = ''
	@Input() markerEnd = ''
	@Input() markerStart = ''
	@Input() source: Coordinates = { x: 0, y: 0 }
	@Input() target: Coordinates = { x: 0, y: 0 }
	@Input() variant?: 'dash-sm' | 'dash-md' | 'dash-lg' | 'dash-xl' | 'double' | 'tunnel'
	@Input() path = ''

	pathClasses = ''
	namespace = `${carbonPrefix}--cc--edge`
	straight = buildStraightPathString
}

// packages/charts-react/src/diagrams/Edge.tsx
import React from 'react'
import classnames from 'classnames'
import { Component as CarbonComponent } from '@carbon/charts'
import { carbonPrefix } from './utils'

type Coordinates = {
	x: number
	y: number
}
type EdgeProps = {
	color?: string
	markerStart?: string
	markerEnd?: string
	source?: Coordinates
	target?: Coordinates
	path?: string
	variant?: string // 'dash-sm' | 'dash-md' | 'dash-lg' | 'dash-xl' | 'double' | 'tunnel'
}

const Edge: React.FC<EdgeProps & React.SVGProps<SVGGElement>> = ({
	color,
	markerEnd,
	markerStart,
	path,
	source,
	target,
	variant = null,
	...rest
}: any) => {
	const namespace = `${carbonPrefix}--cc--edge`
	const pathClasses = classnames(namespace, {
		[`${namespace}--${variant}`]: variant,
		[rest.className]: rest.className
	})

	const d = path || CarbonComponent.buildStraightPathString(source, target)

	return (
		<g className={pathClasses} {...rest}>
			<path d={d} className={`${namespace}__container`} />
			<path d={d} className={`${namespace}__outer`} />
			<path
				d={d}
				className={`${namespace}__inner`}
				markerEnd={`url(#${markerEnd})`}
				markerStart={`url(#${markerStart})`}
				style={{ stroke: color }}
			/>
		</g>
	)
}

export default Edge
