// packages/angular/src/components/graph/edge/edge.component.ts
import { Component, Input } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";
import { straight } from "./buildPath";

const { prefix } = settings;

@Component({
	selector: "[ibm-graph-edge]",
	template: `
	<svg:path
		[attr.d]="path ? path : straight(source, target)"
		[ngClass]="[namespace, variant && namespace + '--' + variant]"
	/>
	`
})

export class EdgeComponent {
	@Input() source;
	@Input() target;
	@Input() variant;
	@Input() path;

	pathClasses;
	namespace = `${prefix}--cc--edge`;
	straight = straight;
}

// packages/react/src/components/edge/edge.js
import React from 'react';
import settings from 'carbon-components/src/globals/js/settings';
import buildPathString from './buildPath';

const { prefix } = settings;

export default ({ source, target }) => {
	const namespace = `${prefix}--cc--edge`;
	const pathString = buildPathString(source, target);

	return (
	<path
		d={pathString}
		strokeWidth={1}
		className={namespace}
		strokeDasharray={0}
	/>
	);
};
