// packages/react/src/diagrams/CardNode/CardNodeLabel.tsx
import React from 'react';
import PropTypes from 'prop-types';

// @ts-ignore
import settings from 'carbon-components/src/globals/js/settings';

const { prefix } = settings;
const namespace = `${prefix}--cc--card-node`;

const CardNodeLabel = ({ children }: any) => (
	<label className={`${namespace}__label`}>{children}</label>
);

export { CardNodeLabel };

CardNodeLabel.propTypes = {
	/**
	 * Pass in the children that will be rendered within the CardNodeLabel
	 */
	children: PropTypes.node,
};

// packages/angular/src/diagrams/card-node/card-node-label.component.ts
import { Component } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";

const { prefix } = settings;

@Component({
	selector: "ibm-diagram-card-node-label",
	template: `
	<xhtml:label [ngClass]="namespace">
		<ng-content></ng-content>
	</xhtml:label>
	`
})

export class CardNodeLabelComponent {
	namespace = `${prefix}--cc--card-node__label`;
}
