// packages/react/src/diagrams/CardNode/CardNodeColumn.tsx
import React from 'react';
import PropTypes from 'prop-types';

// @ts-ignore
import settings from 'carbon-components/src/globals/js/settings';

const { prefix } = settings;
const namespace = `${prefix}--cc--card-node`;

const CardNodeColumn = ({ children, farsideColumn }: any) => (
	<div
		className={`${namespace}__column ${
			farsideColumn && `${namespace}__column--farside`
		}`}>
		{children}
	</div>
);

export { CardNodeColumn };

CardNodeColumn.propTypes = {
	/**
	 * Pass in the children that will be rendered within the CardNodeColumn
	 */
	children: PropTypes.node,

	/**
	 * Specify whether this is the last column
	 */
	farsideColumn: PropTypes.bool,
};

// packages/angular/src/diagrams/card-node/card-node-column.component.ts
import { Component, Input, HostBinding } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";

const { prefix } = settings;


@Component({
	selector: "ibm-diagram-card-node-column",
	template: `
	<xhtml:div>
		<ng-content></ng-content>
	</xhtml:div>
	`
})

export class CardNodeColumnComponent {
	@Input() farsideColumn = false;

	@HostBinding("class") get class() {
		return `${prefix}--cc--card-node__column ${this.farsideColumn ? `${prefix}--cc--card-node__column--farside` : ""}`;
	}
}
