// packages/react/src/diagrams/CardNode/CardNodeTitle.tsx
import React from 'react';
import PropTypes from 'prop-types';

// @ts-ignore
import settings from 'carbon-components/src/globals/js/settings';

const { prefix } = settings;
const namespace = `${prefix}--cc--card-node`;

const CardNodeTitle = ({ children }: any) => (
	<div className={`${namespace}__title`}>{children}</div>
);

export { CardNodeTitle };

CardNodeTitle.propTypes = {
	/**
	 * Pass in the children that will be rendered within the CardNodeTitle
	 */
	children: PropTypes.node,
};

// packages/angular/src/diagrams/card-node/card-node-title.component.ts
import { Component } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";

const { prefix } = settings;

@Component({
	selector: "ibm-diagram-card-node-title",
	template: `
	<xhtml:div [ngClass]="namespace">
		<ng-content></ng-content>
	</xhtml:div>
	`
})

export class CardNodeTitleComponent {
	namespace = `${prefix}--cc--card-node__title`;
}
