// packages/angular/src/components/diagrams/card-node/card-node.component.ts
import { Component, Input, Output, EventEmitter, TemplateRef } from "@angular/core";
import settings from "carbon-components/src/globals/js/settings";

const { prefix } = settings;

@Component({
	selector: "ibm-diagram-card-node",
	template: `
	<xhtml:div [ngClass]="[namespace, stacked ? namespace + '--stacked' : '']" [ngStyle]="{'border-color': color}" tabindex="0" (click)="onClick.emit($event)">
		<div *ngIf="renderIcon" attr.class="{{ namespace + '__icon' }}" >
			<ng-container *ngTemplateOutlet="renderIcon"></ng-container>
		</div>
		<div attr.class="{{ namespace + '__body' }}">
            <div attr.class="{{ namespace + '__title' }}">{{title}}</div>
            <div attr.class="{{ namespace + '__description' }}">{{description}}</div>
			<div *ngIf="label" attr.class="{{ namespace + '__label' }}">{{label}}</div>
		</div>
		<div *ngIf="renderAction" attr.class="{{ namespace + '__action' }}" >
			<ng-container *ngTemplateOutlet="renderAction"></ng-container>
		</div>
	</xhtml:div>
	`
})

export class CardNodeComponent {
	@Input() color;
	@Input() description;
	@Input() label;
	@Input() stacked;
	@Input() title;
	@Input() renderAction: TemplateRef<any>;
	@Input() renderIcon: TemplateRef<any>;
	@Output() onClick = new EventEmitter<any>();

	namespace = `${prefix}--cc--card-node`;
}

// packages/react/src/components/diagrams/CardNode/CardNode.js
import React from 'react';
import settings from 'carbon-components/src/globals/js/settings';
import classnames from 'classnames';

const { prefix } = settings;
const namespace = `${prefix}--cc--card-node`;

const CardNode = ({ as = "div", children, color, href = null, onClick = null, stacked }) => {
	let Component = 'div';

	if (as !== 'div') {
		Component = as;
	} else if (href) {
		Component = 'a';
	} else if (onClick) {
		Component = 'button';
	}

	const cardClasses = classnames(namespace, {
		[`${namespace}--stacked`]: stacked,
		[`${namespace}--${Component}`]: Component,
	});

	return (
		<Component className={cardClasses} tabIndex={0} onClick={onClick} style={{ borderColor: color }} >
			{children}
		</Component>
	);
};

const CardNodeColumn = ({children, farsideColumn}) => <div className={`${namespace}__column ${farsideColumn && `${namespace}__column--farside` }`}>{children}</div>;
const CardNodeDescription = ({children}) => <p className={`${namespace}__description`}>{children}</p>;
const CardNodeLabel = ({children}) => <label className={`${namespace}__label`}>{children}</label>;
const CardNodeTitle = ({children}) => <h2 className={`${namespace}__title`}>{children}</h2>;

export {
	CardNode as default,
	CardNodeColumn,
	CardNodeDescription,
	CardNodeLabel,
	CardNodeTitle
}
