// packages/react/src/charts/boxplot-chart.tsx
import React from 'react'
import {
	BoxplotChart as BoxplotChartCore,
	type BoxplotChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class BoxplotChart extends BaseChart<BoxplotChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new BoxplotChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as BoxplotChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
	}
}

// packages/svelte/src/lib/BoxplotChart.svelte
<script lang="ts">
	import {
		BoxplotChart as BoxplotChartCore,
		type BoxplotChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: BoxplotChartCore
	export let options: BoxplotChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={BoxplotChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />
