// packages/react/src/charts/BoxplotChart.tsx
import React from 'react'
import {
	BoxplotChart as BoxplotChartCore,
	type BoxplotChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './BaseChart'

export default class BoxplotChart extends BaseChart<BoxplotChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: BoxplotChartOptions) {
		return new BoxplotChartCore(chartRef, { data, options })
	}
}

// packages/svelte/src/lib/BoxplotChart.svelte
<script lang="ts">
	import {
		BoxplotChart as BoxplotChartCore,
		type BoxplotChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: BoxplotChartCore
	export let options: BoxplotChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={BoxplotChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />
