// packages/react/src/charts/BubbleChart.tsx
import React from 'react'
import { BubbleChart as BubbleChartCore, type BubbleChartOptions, type ChartTabularData } from '@carbon/charts'
import BaseChart from './BaseChart'

export default class BubbleChart extends BaseChart<BubbleChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: BubbleChartOptions) {
		return new BubbleChartCore(chartRef, { data, options })
	}
}

// packages/svelte/src/lib/BubbleChart.svelte
<script lang="ts">
	import {
		BubbleChart as BubbleChartCore,
		type BubbleChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: BubbleChartOptions
	export let data: ChartTabularData
	export let chart: BubbleChartCore
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={BubbleChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />
