// packages/react/src/charts/bubble-chart.tsx
import React from 'react'
import {
	BubbleChart as BubbleChartCore,
	type BubbleChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class BubbleChart extends BaseChart<BubbleChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new BubbleChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as BubbleChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
	}
}

// packages/svelte/src/lib/BubbleChart.svelte
<script lang="ts">
	import {
		BubbleChart as BubbleChartCore,
		type BubbleChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: BubbleChartOptions
	export let data: ChartTabularData
	export let chart: BubbleChartCore
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={BubbleChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />
