// packages/react/src/charts/bullet-chart.tsx
import React from 'react'
import {
	BulletChart as BulletChartCore,
	type BulletChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class BulletChart extends BaseChart<BulletChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new BulletChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as BulletChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => { if (chartRef) this.chartRef = chartRef }} className="chart-holder"></div>
	}
}

// packages/svelte/src/lib/BulletChart.svelte
<script lang="ts">
	import {
		BulletChart as BulletChartCore,
		type BulletChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: BulletChartOptions
	export let data: ChartTabularData
	export let chart: BulletChartCore | null = null
	export let ref: HTMLDivElement | null = null
</script>

<BaseChart
	{...$$restProps}
	Chart={BulletChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />
