// packages/react/src/charts/GaugeChart.tsx
import React from 'react'
import {
	GaugeChart as GaugeChartCore,
	type GaugeChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './BaseChart'

export default class GaugeChart extends BaseChart<GaugeChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: GaugeChartOptions) {
		return new GaugeChartCore(chartRef, { data, options })
	}
}

// packages/svelte/src/lib/GaugeChart.svelte
<script lang="ts">
	import {
		GaugeChart as GaugeChartCore,
		type GaugeChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: GaugeChartOptions
	export let data: ChartTabularData
	export let chart: GaugeChartCore | undefined = undefined
	export let ref: HTMLDivElement | undefined = undefined
</script>

<BaseChart
	{...$$restProps}
	Chart={GaugeChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />
