// packages/react/src/charts/heatmap-chart.tsx
import React from 'react'
import {
	HeatmapChart as HeatmapChartCore,
	type HeatmapChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class HeatmapChart extends BaseChart<HeatmapChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new HeatmapChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as HeatmapChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => { if (chartRef) this.chartRef = chartRef }} className="chart-holder"></div>
	}
}

// packages/svelte/src/lib/HeatmapChart.svelte
<script lang="ts">
	import {
		HeatmapChart as HeatmapChartCore,
		type HeatmapChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: HeatmapChartOptions
	export let data: ChartTabularData
	export let chart: HeatmapChartCore | null  = null
	export let ref: HTMLDivElement | null  = null
</script>

<BaseChart
	{...$$restProps}
	Chart={HeatmapChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />
