// packages/charts-react/src/charts/histogram-chart.tsx
import {
	HistogramChart as HistogramChartCore,
	type HistogramChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class HistogramChart extends BaseChart<HistogramChartOptions> {
	declare chartRef: HTMLDivElement

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new HistogramChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as HistogramChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
	}
}

// packages/svelte/src/lib/HistogramChart.svelte
<script lang="ts">
	import { HistogramChart as HistogramChartCore, type HistogramChartOptions, type ChartTabularData } from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: HistogramChartCore
	export let options: HistogramChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={HistogramChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />
