// packages/charts-react/src/pie-chart.tsx
import {
	PieChart as PieChartCore,
	type PieChartOptions,
	type ChartConfig,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class PieChart extends BaseChart<PieChartOptions> {
	declare chartRef: HTMLDivElement
	declare props: ChartConfig<PieChartOptions>
	declare chart: PieChartCore

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new PieChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as PieChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
	}
}

// packages/svelte/src/lib/PieChart.svelte
<script lang="ts">
	import {
		PieChart as PieChartCore,
		type PieChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: PieChartOptions
	export let data: ChartTabularData
	export let chart: PieChartCore | null  = null
	export let ref: HTMLDivElement | null  = null
</script>

<BaseChart
	{...$$restProps}
	Chart={PieChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />
