// packages/react/src/charts/TreeChart.tsx
import React from 'react'
import {
	TreeChart as TreeChartCore,
	type TreeChartOptions,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './BaseChart'

export default class TreeChart extends BaseChart<TreeChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: TreeChartOptions) {
		return new TreeChartCore(chartRef, { data, options })
	}
}

// packages/svelte/src/lib/TreeChart.svelte
<script lang="ts">
	import {
		TreeChart as TreeChartCore,
		type TreeChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: TreeChartOptions
	export let data: ChartTabularData
	export let chart: TreeChartCore
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={TreeChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />
