// packages/react/src/charts/TreemapChart.tsx
import React from 'react'
import { TreemapChart as TreemapChartCore, type TreemapChartOptions, type ChartTabularData } from '@carbon/charts'
import BaseChart from './BaseChart'

export default class TreemapChart extends BaseChart<TreemapChartOptions> {
	createChart(chartRef: HTMLDivElement, data: ChartTabularData, options: TreemapChartOptions) {
		return new TreemapChartCore(chartRef, { data, options })
	}
}

// packages/svelte/src/lib/TreemapChart.svelte
<script lang="ts">
	import {
		TreemapChart as TreemapChartCore,
		type TreemapChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: TreemapChartCore
	export let options: TreemapChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={TreemapChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />
