// packages/charts-react/src/charts/wordcloud-chart.tsx
import {
	WordCloudChart as WordCloudChartCore,
	type WorldCloudChartOptions,
	type ChartConfig,
	type ChartTabularData
} from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class WordCloudChart extends BaseChart<WorldCloudChartOptions> {
	declare chartRef: HTMLDivElement
	declare props: ChartConfig<WorldCloudChartOptions>
	declare chart: WordCloudChartCore

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new WordCloudChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as WorldCloudChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
	}
}

// packages/svelte/src/lib/WordCloudChart.svelte
<script lang="ts">
	import {
		WordCloudChart as WordCloudChartCore,
		type WorldCloudChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let options: WorldCloudChartOptions
	export let data: ChartTabularData
	export let chart: WordCloudChartCore | null  = null
	export let ref: HTMLDivElement | null  = null
</script>

<BaseChart
	{...$$restProps}
	Chart={WordCloudChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />
