// packages/svelte/src/lib/BarChartStacked.svelte
<script lang="ts">
	import { StackedBarChart as StackedBarChartCore, type BarChartOptions, type ChartTabularData } from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'
	export let chart: StackedBarChartCore
	export let options: BarChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={StackedBarChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/charts-react/src/bar-chart-stacked.tsx
import { StackedBarChart as StackedBarChartCore, type StackedBarChartOptions, type ChartConfig, type ChartTabularData } from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class StackedBarChart extends BaseChart<StackedBarChartOptions> {
	declare chartRef: HTMLDivElement
	declare props: ChartConfig<StackedBarChartOptions>
	declare chart: StackedBarChartCore

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new StackedBarChartCore(this.chartRef, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as StackedBarChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
	}
}
