// packages/svelte/src/lib/LineChart.svelte
<script lang="ts">
	import {
		LineChart as LineChartCore,
		type LineChartOptions,
		type ChartTabularData
	} from '@carbon/charts'
	import BaseChart from './BaseChart.svelte'

	export let chart: LineChartCore
	export let options: LineChartOptions
	export let data: ChartTabularData
	export let ref: HTMLDivElement
</script>

<BaseChart
	{...$$restProps}
	Chart={LineChartCore}
	{options}
	{data}
	bind:ref
	bind:chart
	on:load
	on:update
	on:destroy />

// packages/charts-react/src/line-chart.tsx
import { LineChart as LineChartCore, type LineChartOptions, type ChartConfig, type ChartTabularData } from '@carbon/charts'
import BaseChart from './base-chart'
import { hasChartBeenInitialized } from './utils'

export default class LineChart extends BaseChart<LineChartOptions> {
	declare chartRef: HTMLDivElement
	declare props: ChartConfig<LineChartOptions>
	declare chart: LineChartCore

	componentDidMount() {
		if (hasChartBeenInitialized(this.chartRef) === false) {
			this.chart = new LineChartCore(this.chartRef!, {
				data: this.props.data as ChartTabularData,
				options: this.props.options as LineChartOptions
			})
		}
	}

	render() {
		return <div ref={(chartRef) => (this.chartRef = chartRef!)} className="chart-holder"></div>
	}
}
